version: "3"

services:
  gogs:
    image: gogs/gogs
    volumes:
      - "gogs_data:/data"
    ports:
      - "10022:22"
      - "3000:3000"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "$PG_DATABASE"
      POSTGRES_USER: "$PG_USER"
      POSTGRES_PASSWORD: "$PG_PASSWORD"

volumes:
  gogs_data:
  pg_data: